apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-name
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name : myfrontend 
      image : nginx:latest
      volumeMounts:
      - mountPath: "/var/www/html"
        name : mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc-name  